In [1]:
import numpy as np

# Задача №1

In [ ]:
# Создайте нулевой вектор размера 10.

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Задача №2

In [16]:
# Как узнать размер в памяти массива Z.
Z = np.zeros((10,10))

In [14]:
Z.size

100

In [17]:
Z.itemsize

8

In [18]:
Z.nbytes

800

# Задача №3

In [27]:
# Создайте нулевой вектор размера 10, но пятое значение равно 1

arr = np.zeros(10)

In [28]:
arr[4] = 1

In [29]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Задача №4

In [32]:
# Создайте вектор со значениями в диапазоне от 10 до 20

np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# Задача №5

In [33]:
# Разверните вектор Z (первый элемент становится последним, а последний первым)

Z = np.arange(10)


In [34]:
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
np.flip(Z)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задача №6

In [42]:
# Создайте матрицу 3x3 со значениями в диапазоне от 0 до 8. Используйте arange и reshape.

arr = np.arange(0,9)
arr = arr.reshape(3,3)



In [49]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Задача №7

In [47]:
# Найдите индексы ненулевых элементов массива Z. Ответ представьте в виде одномерного массива.

arr[arr == 0]


array([0])

In [57]:
ind = np.where(arr != 0)

In [59]:
np.array(ind)

array([[0, 0, 1, 1, 1, 2, 2, 2],
       [1, 2, 0, 1, 2, 0, 1, 2]], dtype=int64)

In [62]:
# также можно использовать:
print(np.where(arr != 0))
print(np.nonzero(arr))

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))
(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))


# Задача №8

In [63]:
# Создайте единичную матрицу 3х3

In [69]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Задача №9

In [70]:
# Найдите наименьшее и наибольшее значение массива Z

Z = np.array([1,2,0,0,4,0])


In [73]:
print(Z.min(), Z.max())

0 4


# Задача №10

In [101]:
# Создайте матрицу размером 5х5, где по краям будут единицы, а в центре нули.

arr = np.zeros([5,5])

In [102]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [103]:
arr[0] = 1

In [104]:
arr

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
arr[-1] = 1

In [106]:
arr

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [107]:
arr[:,0] = 1

In [108]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [109]:
arr[:,-1] = 1

In [110]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [111]:
# Решение мастера
Z = np.ones((5,5))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Задача №11



In [13]:
# Создайте матрицу 5x5 со значениями 1,2,3,4 чуть ниже диагонали

arr = np.zeros((4,5))

In [18]:
diag = np.linspace(1, 4, 4)

In [19]:
diag

array([1., 2., 3., 4.])

In [20]:
np.fill_diagonal(arr, diag)

In [21]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [30]:
top = np.zeros(5)

In [31]:
top

array([0., 0., 0., 0., 0.])

In [35]:
answer = np.zeros((5,5))

In [37]:
answer[0] = top

In [38]:
answer[1:] = arr

In [40]:
answer.astype('int64')

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]], dtype=int64)

In [42]:
print(answer.astype('int64'))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [43]:
arr = np.zeros((5,5))

In [44]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.fill_diagonal(arr[1:], [1,2,3,4])

In [46]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

# Задача №12

In [80]:
# Создайте матрицу 8x8 и заполните ее в шахматном порядке.


arr = np.zeros((8,8))

In [48]:
lst = [0, 1]

In [68]:
lst*5

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

In [75]:
chess_1 = (lst*5)[2:]

In [76]:
chess_1

[0, 1, 0, 1, 0, 1, 0, 1]

In [77]:
chess_2 = (lst*5)[1:-1]

In [78]:
chess_2

[1, 0, 1, 0, 1, 0, 1, 0]

In [84]:
arr[[0, 2, 4, 6]] = chess_1

In [64]:
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [85]:
arr[[1, 3, 5, 7]] = chess_2

In [86]:
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# Задача №13

In [87]:
# Нормализуйте матрицу Z (под нормализовать, подразумевается стандартизировать)

Z = np.array([[1,2,3,4,5], [5,4,3,2,1], [1,2,3,4,5], [5,4,3,2,1]])

In [95]:
Z

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [97]:
# Формула нормализации:

# в числителе значение элемента массива минус среднее значение, 
# в знаменателе стандартное отклонение (вычисляется как np.std(Z))

# Yi = (Xi - Xmean) / np.std(Z)


In [98]:
Z = (Z-Z.mean()) / np.std(Z)

In [99]:
Z

array([[-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [ 1.41421356,  0.70710678,  0.        , -0.70710678, -1.41421356],
       [-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356],
       [ 1.41421356,  0.70710678,  0.        , -0.70710678, -1.41421356]])

# Задача №14

In [101]:
# Выполните матричное умножение А и B

A = np.ones((5,3))
B = np.ones((3,2))

In [102]:
np.dot(A, B)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [103]:
A@B

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# Задача №15

In [6]:
# Выполните умножение на -1 те значения, которые больше 3, но меньше 8. 

Z = np.arange(11)

In [105]:
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
np.where(Z > 3, np.where(Z < 8, Z*(-1), Z), Z)

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

# Задача № 16

In [16]:
# Как найти общие значения между двумя массивами Z1 и Z2?

Z1 = np.array([1, 2, 3, 4, 5])
Z2 = np.array([6, 7, 8, 9, 5, 4])

In [20]:
list(set(Z1) & set(Z2))

[4, 5]

In [30]:
np.array(list(set(Z1) & set(Z2)))

array([4, 5])

In [25]:
np.intersect1d(Z1, Z2)

array([4, 5])

In [26]:
Z1[np.in1d(Z1, Z2)]

array([4, 5])

In [29]:
Z1[np.isin(Z1, Z2)]

array([4, 5])