In [2]:
import numpy as np

# Задача №17

In [2]:
# Вычислите ((A+B)*(-A/2)) без копирования массивов.

# Используйте функции: add, negative, divide, multiply
    
A = np.ones(3)*1
B = np.ones(3)*2

In [3]:
A

array([1., 1., 1.])

In [4]:
B

array([2., 2., 2.])

In [6]:
np.add(A, B)

array([3., 3., 3.])

In [7]:
np.negative(A)

array([-1., -1., -1.])

In [8]:
np.divide(np.negative(A), 2)

array([-0.5, -0.5, -0.5])

In [12]:
print(np.multiply(np.add(A, B), (np.divide(np.negative(A), 2))))

[-1.5 -1.5 -1.5]


# Задача №18

In [ ]:
# Создайте матрицу 5x5 со значениями строк в диапазоне от 0 до 4.

In [19]:
mtrx = np.zeros((5,5))
mtrx

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
mtrx[0]

array([0., 0., 0., 0., 0.])

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
for i in range(5):
    mtrx[i] = np.arange(0,5)    

In [27]:
mtrx

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [33]:
# А вот и классный ответ:
    
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# Задача №19

In [40]:
# Создайте вектор размера 10 со значениями в диапазоне от 0 до 1. (0 и 1 не должны входить)

np.linspace(0, 1, num = 11, endpoint = False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

# Задача №20

In [42]:
# Выполните сортировку массива Z

Z = np.array([6, 9, 5, 7, 8, 4])

In [44]:
sorted(Z)

[4, 5, 6, 7, 8, 9]

# Задача №21

In [45]:
0.3 == 3 * 0.1

False

In [46]:
x = 0.3
y = 3 * 0.1
print(x, y)

0.3 0.30000000000000004


# Задача №22

In [47]:
np.array(0)

array(0)

In [48]:
np.array(0) / np.array(0)

C:\Users\roman\AppData\Local\Temp\ipykernel_2668\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [49]:
np.array(0) // np.array(0)

C:\Users\roman\AppData\Local\Temp\ipykernel_2668\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [51]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [54]:
Z

array([6, 9, 5, 7, 8, 4])

In [57]:
#см. python >> битовые операторы
2 << Z

array([ 128, 1024,   64,  256,  512,   32], dtype=int32)

# Задача №23

In [58]:
# Проверьте, равны ли элементы массивов A и B в пределах допуска, 
# который равен 1 (проверка на приблизительное равенство).

In [59]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([2, 3, 4, 5, 6])

In [61]:
A == B

array([False, False, False, False, False])

In [73]:
a = 0
for i in range(len(A)):
    if A[i] == B[i] or A[i] == B[i]+1 or A[i] == B[i]-1:
        pass
    else:
        a +=1

if a == 0:
    print(True)

True


In [78]:
# Внимание правильный ответ:


print(np.allclose(A, B, rtol=1))

# или 
print(all(np.abs(A-B) <= 1))

True
True


# Задача №24

In [101]:
# Матрица Z размером 10x2, содержит декартовы координаты. Преобразуйте их в полярные координаты.

Z = np.array([[0.64414354, 0.38074849],
               [0.66304791, 0.16365073],
               [0.96260781, 0.34666184],
               [0.99175099, 0.2350579 ],
               [0.58569427, 0.4066901 ],
               [0.13623432, 0.54413629],
               [0.51817635, 0.76685511],
               [0.93385014, 0.08970338],
               [0.19577126, 0.99419368],
               [0.2351805 , 0.23898637]])

In [122]:
r = []
ang = []
for i in range(len(Z)):
    r.append(np.sqrt(Z[i][0]**2 + Z[i][1]**2))
    ang.append(np.arctan(Z[i][1]/Z[i][0]))

In [123]:
print(np.array(r), np.array(ang))

[0.74825819 0.68294516 1.02312669 1.0192263  0.71304601 0.56093145
 0.92551255 0.93814859 1.01328548 0.33529741] [0.53384421 0.24197957 0.34566872 0.23271877 0.60693925 1.32547133
 0.97655486 0.09576376 1.37636924 0.79342443]


# Задача №25

In [3]:
# Имея массивы X и Y постройте матрицу Коши: C (Cij =1/(xi - yj))а затем посчитайте детерминант.


X = np.arange(8)
Y = X + 0.5

In [5]:
X

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
Y

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5])

In [13]:
Z = np.zeros((8,8))

In [14]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
for i in range(8):
    for j in range(8):
        Z[i,j] = 1 / (X[i] - Y[j])

In [16]:
Z

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [17]:
det = np.linalg.det(Z)

In [18]:
det

3638.1636371179666

# Задача №26

In [19]:
# Найдите ближайшее значение (к заданному скаляру v) в векторе Z?

Z = np.arange(100)
v = 68.2139380784148

In [31]:
# решение через заданную точность, оно вообще работает только для этого случая:
int(Z[np.isclose(Z, v, atol=.22)])

68

In [34]:
Z[np.isclose(Z, v, atol=.9)]

array([68, 69])

In [35]:
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
abs(Z-v)

array([68.21393808, 67.21393808, 66.21393808, 65.21393808, 64.21393808,
       63.21393808, 62.21393808, 61.21393808, 60.21393808, 59.21393808,
       58.21393808, 57.21393808, 56.21393808, 55.21393808, 54.21393808,
       53.21393808, 52.21393808, 51.21393808, 50.21393808, 49.21393808,
       48.21393808, 47.21393808, 46.21393808, 45.21393808, 44.21393808,
       43.21393808, 42.21393808, 41.21393808, 40.21393808, 39.21393808,
       38.21393808, 37.21393808, 36.21393808, 35.21393808, 34.21393808,
       33.21393808, 32.21393808, 31.21393808, 30.21393808, 29.21393808,
       28.21393808, 27.21393808, 26.21393808, 25.21393808, 24.21393808,
       23.21393808, 22.21393808, 21.21393808, 20.21393808, 19.21393808,
       18.21393808, 17.21393808, 16.21393808, 15.21393808, 14.21393808,
       13.21393808, 12.21393808, 11.21393808, 10.21393808,  9.21393808,
        8.21393808,  7.21393808,  6.21393808,  5.21393808,  4.21393808,
        3.21393808,  2.21393808,  1.21393808,  0.21393808,  0.78

In [41]:
abs(Z-v).min()

0.21393807841479884

In [39]:
np.argwhere(abs(Z-v) == abs(Z-v).min())

array([[68]], dtype=int64)