In [2]:
import numpy as np

print(np.__version__) # 1.20.3

1.24.2


In [2]:
import numpy as np
arr = np.array([5, 3, 2, 0, 7, 12, 9, 1, 3, 4])

In [2]:
arr

NameError: name 'arr' is not defined

# Тип элементов

In [4]:

print(arr.dtype) # int64

int32


In [5]:
# Размерность массива
print(arr.shape) # (10,)

(10,)


In [6]:
import numpy as np
arr = np.array([[5, 3, 2, 0, 7], 
                [4, 5, 7, 13, 6], 
                [7, 3, 2, 6, 2],
                [18, 1, 9, 5, 0]]) 
# Тип элементов
print(arr.dtype) # int64
# Размерность массива
print(arr.shape) # (4, 5)

int32
(4, 5)


In [10]:
# Одномерный массив
lst = [4, 5, 6]
arr = np.array(lst)
print(arr) # [4 5 6]

[4 5 6]


In [11]:
#Одномерный массив
a = np.arange(3, 11, 2) # Начало, конец, шаг
print(a) # [3 5 7 9]
a = np.arange(5) # только количество элементов
print(a) # [0 1 2 3 4]

[3 5 7 9]
[0 1 2 3 4]


In [8]:
# Двумерный массив
lst = [[4, 5, 6], 
       [7, 8, 9]]
arr = np.array(lst)
print(arr) 

[[4 5 6]
 [7 8 9]]


In [9]:
print(arr.shape[0]) # 2 строки
print(arr.shape[1]) # 3 столбца

2
3


In [13]:
#Одномерный массив
a = np.zeros((5))
print(a)
# Результат
# [0. 0. 0. 0. 0.]
a = np.ones(3)
print(a)
# Результат
# [1. 1. 1.]
#Двумерный массив
a = np.zeros((3, 4))
print(a)
# Результат
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]
a = np.ones((2, 3))
print(a)
# Результат 
# [[1. 1. 1.]
#  [1. 1. 1.]]

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#Нули и единицы c размерностью другого массива
#Функции np.zeros_like() и np.ones_like() умеют подглядывать в другие массивы и копировать их размерность и тип данных. 

a = np.array([[1, 2, 3], 
              [4, 5, 6]])

b = np.zeros_like(a)
print(b)
# Результат 
# [[0 0 0]
#  [0 0 0]]
a = np.array([[1, 2, 3], 
              [4, 5, 6]])
b = np.ones_like(a)
print(b)

# Результат
# [[1 1 1]
#  [1 1 1]]

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [15]:
#Случайные числа
#Если нас интересует массив случайных чисел в диапазоне [0; 1), то используем np.random.random() с параметром size, в котором укажем желаемую размерность:

a = np.random.random(size=(2, 2))
print(a)
# Пример результата
# [[0.46288644 0.78587867]
#  [0.3694063  0.09728958]]
#Этот способ позволяет сгенерировать и одно случайное число, можно просто не указывать size

a = np.random.random()

[[0.46611143 0.9584567 ]
 [0.70630408 0.30423647]]


In [16]:
#Случайные целые числа
#Если нас интересуют случайные массив целых чисел, то можно использовать np.random.randint(start, stop, size=None). Первые два числа задают начало и конец диапазона, в котором будут сгенерированы случайные числа. Причем, начало включительно, а конец - нет. 

#Параметр size определяет размерность итогового массива:

a = np.random.randint(1, 20, size=(2, 4))
print(a)
# Пример результата
# [[10  2 14  8]
#  [ 8  7 10 12]]
#Опять же, size можно не указывать, тогда получим одно число

a = np.random.randint(1, 20)
print(a) # 13

[[ 5 16 19  7]
 [10  7 12 14]]
2


In [17]:
#np.linspace()
#Функция генерации линейной последовательности. Генерирует num точек в диапазоне от start до stop

#np.linspace(strart, stop, num=50, endpoint=True, retstep=False) - функция линейной последовательности. Генерирует num элементов, начиная со значения start и заканчивая stop.
#Если endpoint=True, то stop тоже включается в массив. Если retstep=True, то функция возвращает сгенерированный массив и шаг. 

#По умолчанию num=50, endpoint=True, retstep=False

#Пример 1

arr = np.linspace(1, 2, num=5)
print(arr) # [1.   1.25 1.5  1.75 2.  ]
#Пример 2. Вернуть шаг 

arr = np.linspace(1, 2, num=5, retstep=True)
print(arr) # (array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
print(arr[0]) # array([1.  , 1.25, 1.5 , 1.75, 2.  ]) - сам массив
print(arr[1]) # 0.25 - шаг между элементами

[1.   1.25 1.5  1.75 2.  ]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)
[1.   1.25 1.5  1.75 2.  ]
0.25


In [22]:
arr = np.linspace(1,100, num=10, retstep=True)

In [50]:
# Задача 1
# Вводится целое положительное число n. 
# Сгенерируйте одномерный массив длиной n в диапазоне от 0 до 5, и умножьте на 3. 
# Выведите результат.

n = int(input())
arr = np.linspace(0,5,num=n)*3
print(arr)

5
[ 0.    3.75  7.5  11.25 15.  ]


In [75]:
#Задача по вычислению функции для n точек в диапазоне [0;3]
n = int(input())
x = np.linspace(0,3, num = n)
arr = np.array(3*(x**2)+(2*x)+3)
print(arr)


5
[ 3.      6.1875 12.75   22.6875 36.    ]


In [23]:
arr

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

In [27]:
arr = np.arange(0,52, step=2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


In [28]:

arr = np.arange(6)
arr = arr.reshape(2, 3)
print(arr)
# Результат
# [[0 1 2]
#  [3 4 5]]

[[0 1 2]
 [3 4 5]]


In [29]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
arr.reshape(-1) # [0, 1, 2, 3, 4, 5]

array([0, 1, 2, 3, 4, 5])

In [36]:
arr.reshape(1) # [0, 1, 2, 3, 4, 5]

ValueError: cannot reshape array of size 12 into shape (1,)

In [37]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])
arr.flatten() # [0, 1, 2, 3, 4, 5]

array([0, 1, 2, 3, 4, 5])

In [3]:
# reshape(x,-1) - позволяет переформатировать массив на x строк и количество столбцов уж сколько получится

In [6]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [9,8,7]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7]])

In [7]:
arr.reshape(2,-1)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 9, 8, 7]])

In [8]:
arr.reshape(3,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 9, 8, 7]])

In [9]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 8, 7])

In [39]:
arr.shape

(2, 3)

In [40]:
arr.shape[0]

2

In [41]:
arr.shape[1]

3

In [42]:
a = np.arange(10, dtype=float)
print(a)
# [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [44]:
#У однажды созданного массива уже невозможно изменить тип данных. 
#Однако можно создать новый массив на основе старого и указать нужный нам тип данных

a_int = np.random.randint(1, 20, size=(3, 2))
a_float = np.array(a_int, dtype=np.float64)
#Либо можно вызвать функцию astype(type) и указать новый тип

a_int = np.random.randint(1, 20, size=(3, 2))
a_float = a_int.astype(np.float64)

In [46]:
#Сложение, умножение, деление массивов

In [47]:
import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([1, 1, 1])

print(a1 + a2) # [2, 3, 4]
#Вычитание, умножение, деление:

import numpy as np

a1 = np.array([1, 2, 3])
a2 = np.array([2, 2, 2])

print(a1 - a2) # [-1, 0, 1]
print(a1 * a2) # [2, 4, 6]
print(a1 ** a2) # [1, 4, 9]
print(a1 / a2) # [0.5, 1.,  1.5]
print(a1 // a2) # [0, 1, 1]

SyntaxError: invalid syntax (1338749504.py, line 7)

In [48]:
a1 = np.array([1, 2, 3])

print(a1 + 2) # [3, 4, 5]
print(a1 - 2) # [-1, 0, 1]
print(a1 * 2) # [2, 4, 6]
print(a1 ** 2) # [1, 4, 9]
print(a1 / 2) # [0.5, 1.,  1.5]
print(a1 // 2) # [0, 1, 1]

[3 4 5]
[-1  0  1]
[2 4 6]
[1 4 9]
[0.5 1.  1.5]
[0 1 1]


In [ ]:
#Если один массив одномерный, а другой - двумерный, то numpy 
#применит оператор между одномерным массивом и каждом строкой двумерного. 
#При этом обязательно, чтобы длина однмерного массива совпадала 
#с количеством столбцов двумерного, иначе получим ошибку

a = np.array([[1, -1, 3], 
              [2,  1, 5],
              [3, -1, 4]])

b = np.array([1,  4, 0])

print(a + b)
# Результат
# [[2 3 3]
#  [3 5 5]
#  [4 3 4]]

In [49]:
a1 = np.array([1, 2, 3])
a1 += 2

print(a1) # [3, 4, 5]

[3 4 5]


In [ ]:
A = np.array([[1, -1, 3], 
              [2,  1, 5],
              [3, -1, 4]])

B = np.array([[1,  4, 0], 
              [1, -1, 2],
              [2, -1, 1]])

print(A @ B)
# Результат
# [[ 6  2  1]
#  [13  2  7]
#  [10  9  2]]

print(A * B)
# Результат
# [[ 1 -4  0]
#  [ 2 -1 10]
#  [ 6  1  4]]
#Обычная * перемножает массивы поэлементно, @ - по правилам перемножения матриц

In [ ]:
# У каждого арифметического оператора есть функция-синоним

# np.add(a, b) / np.subtract(a, b) - поэлементное сложение/вычитание. Синоним + и - 
# np.multiply(a, b) / np.divide(a, b) / np.true_divide(a, b) - поэлементное произведение/деление. Синоним * и  / 
# np.power(a, b) - поэлементное возведение a в степень b. Синоним **
# np.floor_divide(a, b) - поэлементное деление без остатка. Синоним //
# np.mod(a, b) / np.remainder(a, b) - поэлементное взятие остатка от деления. Синоним %
# np.dot(a, b) - алгебраическое перемножение матриц. Синоним @

In [ ]:
# Математические константы
# np.e - постоянная Эйлера, значение e = 2.718281828...

# np.pi  - число π, значение pi = 3.14159265...

In [ ]:
# 1. Дан массив радиусов нескольких окружностей. 
# С помощью арифметических операторов и константы np.pi вычислить площадь каждой окружности
radius = np.array([ 6, 18,  6, 13, 10])
print(np.pi * radius**2)
# Результат
# [ 113.09733553 1017.87601976  113.09733553  530.92915846  314.15926536]


# 2. Дан массив чисел. Вычислить np.e в степени каждого числа из массива
pow = np.array([ 1, 2,  3])
print(np.e ** pow)
# Результат
# [ 2.71828183  7.3890561  20.08553692]

In [51]:
# np.nan не равна ни одному значению, даже сама себе. Именно поэтому мы не можем использовать такое условие: 

a = np.sqrt(-9) # здесь получится np.nan

if a == np.nan:
     print("a - нечисло")
# Для сравнения с nan нужно использовать специальные функции, например, np.isnan():

a = np.sqrt(-9) # здесь получится np.nan

if np.isnan(a):
    print("a - нечисло")

a - нечисло


C:\Users\roman\AppData\Local\Temp\ipykernel_76404\1069556031.py:3: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(-9) # здесь получится np.nan
C:\Users\roman\AppData\Local\Temp\ipykernel_76404\1069556031.py:9: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(-9) # здесь получится np.nan


In [52]:
# По умолчанию np.nan заменяется на 0

arr = np.array([np.nan, 4, 9, np.nan])
print(np.nan_to_num(arr)) # [0., 4., 9., 0.]


# По умолчанию np.inf заменяется на очень большое вещественное значение


arr = np.array([4, 9, np.inf])
print(np.nan_to_num(arr)) # [4.00000000e+000, 9.00000000e+000, 1.79769313e+308]

# Можно указать, какие значения установить вместо np.nan или np.inf/np.NINF

arr = np.array([np.nan, 4, 9, np.inf, np.NINF])
print(np.nan_to_num(arr, nan=-1, posinf=-2, neginf=-3)) # [-1.  4.  9. -2. -3.]

[0. 4. 9. 0.]
[4.00000000e+000 9.00000000e+000 1.79769313e+308]
[-1.  4.  9. -2. -3.]


In [53]:
#ЗАДАЧИ

In [58]:
# Дан ряд целых чисел. Выведите для каждого числа его последнюю цифру. Решение не должно содержать циклы. 

import numpy as np

a = np.array([10, 25, 24,  3,  7, 17,  9,  2,  1, 27])
arr=a%10


In [59]:
arr

array([0, 5, 4, 3, 7, 7, 9, 2, 1, 7], dtype=int32)

In [74]:
# Обратная последовательность
# Вводятся целые положительные числа n и m. 
# Создайте и выведите целочисленный массив размерностью n x m cо значениями от 1 до n*m в обратном порядке

n = int(input())
m = int(input())

arr = np.arange(n*m, 0, step=-1).reshape(n,m)
print(arr)




10
20
[[200 199 198 197 196 195 194 193 192 191 190 189 188 187 186 185 184 183
  182 181]
 [180 179 178 177 176 175 174 173 172 171 170 169 168 167 166 165 164 163
  162 161]
 [160 159 158 157 156 155 154 153 152 151 150 149 148 147 146 145 144 143
  142 141]
 [140 139 138 137 136 135 134 133 132 131 130 129 128 127 126 125 124 123
  122 121]
 [120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103
  102 101]
 [100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
   82  81]
 [ 80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63
   62  61]
 [ 60  59  58  57  56  55  54  53  52  51  50  49  48  47  46  45  44  43
   42  41]
 [ 40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23
   22  21]
 [ 20  19  18  17  16  15  14  13  12  11  10   9   8   7   6   5   4   3
    2   1]]
