In [1]:
import numpy as np

# Сравнение массивов

### Как сравнить два массива 

In [3]:
# Мы говорили о том, что к массивам применимы все арифметические операторы и они производят поэлементные вычисления. 

# На самом деле, то же касается и операторов сравнения. С помощью ==, !=, <=, <, >, >= можно 
# поэлементно сравнить два массива. В этом случае мы получим массив значений Истина/Ложь, 

# такие массивы называют булевыми или логическими.  


#                                     1     2    False

#                                     2 ==  2 =  True

#                                     3     3    True

In [4]:
# Пример
# 1. Сравнение через оператор ==

a1 = np.array([1, 2, 3])
a2 = np.array([2, 2, 2])

print(a1 == a2) # [False  True False]

[False  True False]


In [5]:
# 2. Сравнение через оператор >

a1 = np.array([1, 2, 3])
a2 = np.array([2, 2, 2])

print(a1 > a2) # [False False  True]

[False False  True]


In [6]:
# 3. Случай, когда один массив двумерный, а другой одномерный, тоже возможен. 
# Тогда одномерный массива будет сравниваться с каждой строкой двумерного:

arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([1, 2])
print(arr1 == arr2)
# Результат
# [[ True  True]
#  [False False]]

[[ True  True]
 [False False]]


### Сравнение массивов с числами

In [7]:
# Можно сравнивать массивы и числа. В этом случае сравниваться будет каждый элемент массива с заданным числом

# Пример

arr1 = np.array([3, 7, 5, 9])
print(arr1 > 5)
# Результат
# [False  True False  True]

[False  True False  True]


In [ ]:
# Функции-синонимы
# Каждый оператор сравнения имеет функцию-синоним

# np.greater(x1, x2) - синоним оператора > 
# np.greater_equal(x1, x2) - синоним оператора >= 
# np.less(x1, x2) - синоним оператора < 
# np.less_equal(x1, x2) - синоним оператора <= 
# np.equal(x1, x2) - синоним оператора == 
# np.not_equal(x1, x2) - синоним оператора !=

# Индексация булевыми массивами

In [ ]:
Можно не только сравнивать массивы, но и извлекать значения, подходящие по условию. 

Мы можем передавать булевы массивы в качестве индексов, тогда в результате вернется 
выборка из массива, которой в исходном массиве было сопоставлено значение True.

In [ ]:
# Пример
# Например, перед нами стоит следующая задача. Создается массив, находится 
# его среднее арифметическое и проверяется, какие элементы строго больше среднего арифметического. 
# Дальше нужно из массива выбрать и вывести эти элементы. 

arr = np.array([3, 4, 5, 1])
mean = np.mean(arr) # 3.25
condition = arr > mean # [False,  True,  True, False]
print(arr[condition]) # [4, 5]

# Чаще это записывается так

arr = np.array([3, 4, 5, 1])
mean = np.mean(arr) # 3.25
print(arr[arr > mean]) # [4, 5]

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9,8,7,6,7,8,7,6,6,5,6,7,8,6,5,5,4,4,3,2,2,1,23,4,5,6,7,7,6,5,0])

In [9]:
a_mean = np.mean(a)

In [10]:
a[a>a_mean]

array([ 6,  7,  8,  9,  8,  7,  6,  7,  8,  7,  6,  6,  6,  7,  8,  6, 23,
        6,  7,  7,  6])

In [ ]:
# Но такой способ работает только, когда нам достаточно только одного условия. 
# Если бы мы хотели извлечь, все элементы, которые больше 1 и меньше 5, 
# то следующая запись была бы ошибкой

arr = np.array([3, 4, 5, 1])
print(arr[arr > 1 and arr < 5]) # Error!

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  8,  7,  6,  7,  8,  7,  6,  6,
        5,  6,  7,  8,  6,  5,  5,  4,  4,  3,  2,  2,  1, 23,  4,  5,  6,
        7,  7,  6,  5,  0])

In [16]:
# Задача

# Дан одномерный массив. Выберите и выведите из массива элементы, которые строго меньше 25 процентиля.

arr = np.array([2, 7, 7, 8, 8, 6, 8, 7, 6, 7])

In [20]:
percentile = np.percentile(arr, 25)

In [21]:
percentile

6.25

In [22]:
arr[arr<percentile]

array([2, 6, 6])