In [2]:
import numpy as np

# Индексы в двумерных массивах

In [3]:

# Предположим, мы имеем двумерный массив:

a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19]])
# В этом массиве 5 строк и 4 столбца, при этом строки имеют свои индексы, а столбцы - свои.

# Чтобы получить элемент в таком массиве, мы должны через запятую указать номер строки и столбца

print(a[1, 2]) # выведет 6
# Если укажем только одно число, то получим строку

print(a[1]) # выведет [ 4,  5,  6,  7]

6
[4 5 6 7]


In [4]:
a.shape[0]

5

In [4]:
a.shape[1]

4

In [4]:
# По индексу можно не только извлекать элементы, но и изменять

# 1. Один элемент

a = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19]])

# Можно указать, например, следующее

a[0, 0] = 3

# Тогда в массиве появится тройка

a = np.array([[ 3, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19]])

# 2. Замена строки. Способ 1

# Можно изменить значение целой строки

a[1] = [40, 50, 50, 70]

# Получится

a = np.array([[ 0, 1, 2, 3],
              [40, 50, 50, 70],
              [ 8, 9, 10, 11],
              [12, 13, 14, 15],
              [16, 17, 18, 19]])

# 3. Замена строки. Способ 2

# Если строке присвоить число, то все ее элементы станут равными этому числу

a = np.array([[0, 1, 2, 3], [0, 1, 2, 3]])
a[0] = 3

print(a) 
# [[3 3 3 3], 
#  [0 1 2 3]]

# 4. Поменять местами элементы

a[0, 0], a[0, 1] = a[0, 1], a[0, 0]

# Тогда увидим

# a = array([[ 1,  0,  2,  3],
#            [ 4,  5,  6,  7],
#            [ 8,  9, 10, 11],
#            [12, 13, 14, 15],
#            [16, 17, 18, 19]])

[[3 3 3 3]
 [0 1 2 3]]


# Срезы 

In [6]:
# 1. Начало или конец среза можно не указывать, а просто поставить двоеточие. Тогда срез начнется с начала и до конца

data = np.array([ 5, 3, -2, 3, 6, -1, 8])

print(data[:3]) # аналогично data[0:3]
print(data[2:]) # аналогично data[2:data.shape[0] - 1]
print(data[:])  # бессмысленный срез от начала до конца 

[ 5  3 -2]
[-2  3  6 -1  8]
[ 5  3 -2  3  6 -1  8]


In [8]:
# 2. Иногда срезы могут возвращать одно число (как и индексы), но это число всегда будет нулевым элементом нового массива

data = np.array([ 5, 3, -2, 3, 6, -1, 8])

print(data[:1]) # [5]
print(data[2:3]) # [-2]
print(data)

[5]
[-2]
[ 5  3 -2  3  6 -1  8]


In [9]:
# 3. Еще есть интересное применение у среза - переворачивать массивы. 
# Это делается с помощью среза с обратным шагом. Этот прием довольно часто применяется

data = np.array([ 5, 3, -2, 3, 6, -1, 8])

print(data[::-1]) # [ 8 -1  6  3 -2  3  5]

[ 8 -1  6  3 -2  3  5]


In [ ]:
# Срезы в двумерных массивах

In [11]:
# Если мы работаем с двумерном массивом, то при использовании таких же срезов, как в примере выше, получим срез строк

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

print(data[0:3])

[[ 5  3 -2]
 [ 3  6 -1]
 [ 8  4  2]]


In [13]:
# Если мы хотим получить, например, столбцы, начиная с 
# первого, то нужно сначала указать срез для строк - поставим просто 
# двоеточие (то есть извлечем все строки), затем через запятую уточним, какие нас интересуют столбцы 

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

print(data[:, 1:])

[[ 3 -2]
 [ 6 -1]
 [ 4  2]
 [ 1  6]]


In [16]:
print(data[:,2])

[-2 -1  2  6]


In [17]:
# Можно комбинировать срезы по строкам со срезами по столбцам

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

In [19]:
data[:3, 0:2 ]

array([[5, 3],
       [3, 6],
       [8, 4]])

In [20]:
# Также можно комбинировать индексацию и срезы. 
# Этот прием позволяет извлечь один столбец. 
# Технически, нам нужно взять срез всех строк, а затем указать желаемый столбец

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

In [21]:
data[:, 2]

array([-2, -1,  2,  6])

In [31]:
# Изменение элементов по срезу
# Массивы можно изменять по срезу, как и в случае с индексами

# Пример
# Извлечем из строки с индексом 1 два последних
# элемента и укажем, что теперь они равняются [3, 7]. 
# В результате вместо [6, -1] теперь видим в массиве [3, 7].

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])
# print(data[1, 1:])
data[1, 1:] = [3,7]

In [ ]:
Задача 1
С помощью np.arange() cгенерируйте 
одномерный массив целых чисел от -3 до 9 включительно. 
Выведите срез с начала массива до середины. 
Середина одномерного массива вычисляется как arr.shape[0] // 2

In [32]:
arr = np.arange(-3, 10)

In [38]:
print(arr)
print(len(arr))
print(len(arr)//2)
print(arr[:len(arr)//2+1])

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
13
6
[-3 -2 -1  0  1  2  3]


In [ ]:
Задача 2
Cгенерируете двумерный массив размерностью n строк 
и m столбцов с последовательностью от 0 до n*m-1. 
Выведите все его строки, кроме первой и последней

In [50]:
n,m = map(int,input().split())
arr = np.arange(0, n*m).reshape(n, m)
print(arr)
print()
print(arr[1:-1])

5 5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Массивы-индексы

Массивы-индексы - это способ извлечь один или несколько элементов, расположенные в хаотичном порядке

In [53]:
# Примеры
a = np.array([6, 4, 3, 8, 9])
index = np.array([0, 2, 3])
print(a[index]) # [6 3 8]

[6 3 8]


In [56]:
# Извлечение одного элемента возвращает массив

a = np.array([6, 4, 3, 8, 9])
index = np.array([-3])
print(a[index]) # [3]

[3]


In [58]:
# Массив индексов не может быть пустым, мы получим ошибку

a = np.array([6, 4, 3, 8, 9])
index = np.array([])
print(a[index]) # IndexError!

IndexError: arrays used as indices must be of integer (or boolean) type

# Двумерный случай
Для индексации двумерных массивов нужно создавать два массива-индекса и передавать их через запятую. Тогда первый массив будет отвечать за индексы строк, а второй - за индексы столбцов. При этом размерности массивов должны либо совпадать, либо один из массивов должен быть одномерным массивом или числом

#Exploring Fancy Indexing

In [61]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
index_row = np.array([0,1])
index_columns = np.array([0,1])
a[index_row, index_columns]

array([1, 5])

In [73]:
a[[0, 0, 1, 1], [0, 1, 0, 1]]

array([1, 2, 4, 5])

In [ ]:
# Пример
# 1. Два одномерных массива

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

row_index = np.array([0, 2, -1, 1])
col_index = np.array([1, 2, 2, 1])
print(data[row_index, col_index]) # [3 2 6 6]

In [ ]:
# 2. Массив + одномерный массив

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

row_index = np.array([0, 2, -1, 1])
col_index = np.array([1])
print(data[row_index, col_index]) # [3 4 1 6]

In [74]:
data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

In [76]:
data[[0, -1],[0]]

array([5, 9])

In [77]:
# 3. Массив + число 

# То же самое, что массив + одномерный массив

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

row_index = np.array([0, 2, -1, 1])
col_index = 1
print(data[row_index, col_index]) # [3 4 1 6]

[3 4 1 6]


In [78]:
data[[1,2,3], 0]

array([3, 8, 9])

In [ ]:
# 4. Комбинация массива-индекса и среза 

data = np.array([[5, 3, -2], 
                 [3, 6, -1], 
                 [8, 4,  2], 
                 [9, 1,  6]])

row_index = np.array([0, 2])
print(data[row_index, :2]) 

#[[5 3]
# [8 4]]

In [ ]:
# Задача
# Дан двумерный массив. Выведите элементы из 5, 2, и последнего столбца

In [79]:
arr = np.array([[ 7,  8,  9, 10, 11, 12, 13],
                [14, 15, 16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25, 26, 27],
                [28, 29, 30, 31, 32, 33, 34]])

In [80]:
arr

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [87]:
arr[:, [5, 2, -1]] # здесь важно, что первый индекс-срез без квадратных скобок

array([[12,  9, 13],
       [19, 16, 20],
       [26, 23, 27],
       [33, 30, 34]])

# Циклы

# 1. Цикл по индексам

In [90]:
arr = np.array([[ 7,  8,  9, 10, 11, 12, 13],
                [14, 15, 16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25, 26, 27],
                [28, 29, 30, 31, 32, 33, 34]])

In [91]:
arr

array([[ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [92]:
arr.shape

(4, 7)

In [93]:
arr.shape[0]

4

In [94]:
arr.shape[1]

7

In [97]:
arr = np.random.randint(0,100, size=5)

In [98]:
arr

array([83, 29, 98, 38, 85])

In [99]:
for i in range(arr.shape[0]):
    print(f'Индекс: {i},  значение: {arr[i]}') # вывод элемента по индексу

Индекс: 0,  значение: 83
Индекс: 1,  значение: 29
Индекс: 2,  значение: 98
Индекс: 3,  значение: 38
Индекс: 4,  значение: 85


In [100]:
# Этот цикл позволяет изменять элементы, то есть можно написать следущее. 

for i in range(arr.shape[0]):
    arr[i] = arr[i] + 1 # изменение элемента по индексу

print(arr)
# Идея очень похожа на цикл, который часто используется со списками 
# for i in range(len(lst)), только вместо len(lst) у массива будет arr.shape[0]

[84 30 99 39 86]


# 2. Цикл по элементам
Позволяет обращаться к элементам напрямую, без индексов и квадратных скобок
Мы пишем этот цикл без range(), поскольку этом цикле множеством является элемент массива
Для получения значений не нужно (и даже нельзя) обращаться по индексу

In [ ]:
Пример
arr = np.array([2, 6, 6, 7, 1, 3])
Тогда цикл по элементам выглядит вот так. Назовем параметр цикла item, чтобы подчеркнуть, что он не является числом

for item in arr:
    print(item) # вывод элемента

# 2
# 6
# 6
# 7
# 1
# 3
Осторожно! Использование этого типа итерации не позволяет изменять элемент. Посмотрим пример

Попробуем увеличивать элемент на 1. Внутри цикла вроде бы все хорошо

for item in arr:
    item = item + 1
    print(item) # вывод элемента

# 3
# 7
# 7
# 8
# 2
# 4
Однако мы увидим, что массив не изменился, если напишем print за пределами цикла

for item in arr:
    item = item + 1

print(arr) # [2 6 6 7 1 3]
Не используйте цикл по элементам для изменения значений массива 

# 3. Цикл по элементам и индексам (нумерованный)

In [101]:
# Объединяет все достоинства циклов по индексам и по элементам

# можно изменять элементы массива
# можно обращаться к значениям напрямую
# Пример
arr = np.array([2, 6, 6, 7, 1, 3])


#  Записывается нумерованный цикл с помощью функции enumerate()

for index, item in enumerate(arr):
    print(f'Индекс: {index},  значение: {item}') # вывод индекса и элемента

Индекс: 0,  значение: 2
Индекс: 1,  значение: 6
Индекс: 2,  значение: 6
Индекс: 3,  значение: 7
Индекс: 4,  значение: 1
Индекс: 5,  значение: 3


In [102]:
arr

array([2, 6, 6, 7, 1, 3])

In [103]:
for i in range(arr):
    print('hello')

TypeError: only integer scalar arrays can be converted to a scalar index

# Задачи

In [ ]:
Задача №1
Создайте двумерный массив единиц размерностью 5 х 3 с помощью np.ones(), 
домножьте элементы каждой строки на ее индекс, увеличенный на единицу и выведите получившуюся матрицу

In [12]:
arr = np.ones([5,3])

In [106]:
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
for i, j in enumerate(arr):
    arr[i] *=i+1
    

In [115]:
arr

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [13]:
#То же через arr.shape:
for i in range(arr.shape[0]):
    arr[i] *= i+1
    
print(arr)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]


In [ ]:
Задача №2
Создайте двумерный массив нулей размерностью 4 х 3, 
увеличьте элементы каждого столбца на его индекс, умноженный на 3 и выведите получившуюся матрицу

In [14]:
arr = np.zeros((4,3))

In [129]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [135]:
for j in range(arr.shape[1]):
    arr[:, j] += j*3

In [136]:
arr

array([[0., 3., 6.],
       [0., 3., 6.],
       [0., 3., 6.],
       [0., 3., 6.]])

In [ ]:
Задача №3
Вводится целое положительное число n, затем n целых чисел. Запишите эти числа в массив и выведите его.

Примечание. В следующих уроках пригодится шаблон, который вы напишете в этом задании

In [28]:
n = int(input())
lst = []
for i in range(n):
    lst.append(int(input()))
arr = np.array(lst)
print(arr)    

3
1
2
3
[1 2 3]


In [147]:
# Правильное решение:

n = int(input())
arr = np.zeros(n, dtype = 'int32')
for i in range(n):
    arr[i] = int(input())

print(arr)

2
1
2
[1. 2.]


In [ ]:
Задача №4
Вводятся целые положительные числа n и m. 
Затем вводится целочисленный массив размерностью n*m. Считайте массив и выведите его. 

In [158]:
n = int(input())
m = int(input())
arr = np.zeros((n,m), dtype = np.int32)
print(arr)
for i in range(n):
    arr[i] = np.array(list(map(int,input().split())))

print(arr)

5
6
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
1 2 3 4 5 6
1 2 3 4 5 6
1 2 3 4 5 6
1 2 3 4 5 6
1 2 3 4 5 6
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


# Задача. Пятерки по диагонали
Создать и вывести матрицу 5х5 с пятёрками по диагонали, элементы должны иметь вещественный тип данных

In [159]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [160]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i == j:
            arr[i, j] = 5
            
print(arr)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


# Задача. Главная диагональ
Вводится целое положительное число n. Сгенерируйте массив размерностью nxn с последовательностью чисел от 0 до n*n не включительно. 
Выведите главную диагональ массива. Попробуйте решить задачу без использования циклов 

In [161]:
n = int(input())

5


In [163]:
arr = np.arange(n*n).reshape(n,n)

In [164]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [179]:
np.diag(arr)

array([ 0,  6, 12, 18, 24])

In [180]:
np.fill_diagonal(arr, -999)

In [181]:
arr

array([[-999,    1,    2,    3,    4],
       [   5, -999,    7,    8,    9],
       [  10,   11, -999,   13,   14],
       [  15,   16,   17, -999,   19],
       [  20,   21,   22,   23, -999]])

# Четные столбцы
Вводится целое положительное число n. 
Сгенерируйте целочисленный массив размерностью nxn 
с последовательностью чисел от 0 до n*n не включительно. 
Выведите четные столбцы массива, используя только срезы. 

In [36]:
n = int(input())
arr = np.zeros((n,n))
print(arr)
x = 0
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        arr[i,j] = x
        x +=1
print(arr)

5
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]


In [38]:
n = int(input())
arr = np.arange(n*n).reshape(n,n)
print(arr)

5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [43]:
print(arr[:, ::2]) # срезы всегда без [], а вот индексы всегда с ними

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]]


In [ ]:
# Задача №
# Дан одномерный массив. Преобразуйте каждый его элемент по правилу:
#    а =  если четное 3*а, если нечетное 2*а
Попробуйте решить эту задачу без циклов

In [59]:
lst = list(map(int, input().split()))
arr = np.array(lst)
print(arr)
print()
arr = arr*2
arr[::2] = arr[::2]/2*3
print(arr)


1 1 1 1 1 1 1 1 1 1
[1 1 1 1 1 1 1 1 1 1]

[3 2 3 2 3 2 3 2 3 2]


In [64]:
# Правильное решение предыдущей задачи:
lst = list(map(int,input().split()))
arr = np.array(lst)
print(arr)

print(arr[1::2]) # печатает все элементы с первого до конца с шагом 2 (получаются все нечетные индексы)
print(arr[::2]) # печатает все элементы с нулевого до конца с шагом 2 (получается - все четные индексы)

1 2 3 4 5 6 7 8
[1 2 3 4 5 6 7 8]
[2 4 6 8]
[1 3 5 7]


# Змейка
Сгенерируйте массив 4х4 и поверните нечетные строки в обратном порядке

In [111]:
arr = np.arange(16).reshape(4,-1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [109]:
arr = np.arange(16).reshape(4,4)
arr[1] = arr[1][::-1]
arr[3] = arr[3][::-1]
print(arr)

[[ 0  1  2  3]
 [ 7  6  5  4]
 [ 8  9 10 11]
 [15 14 13 12]]


In [ ]:
Правильное решение:
arr = np.arange(4*4).reshape(4, -1)
arr[1::2] = arr[1::2, ::-1]
print(arr)

# Поворот на 90 градусов
Сгенерируйте массив nxn, в котором последовательность от 1 до n**2 повернется на 90 градусов.

In [123]:
n = int(input())
arr = np.arange(1,n**2+1).reshape(n, -1)
print(arr)
print()
print(arr.T)
print()
print(arr.T[::-1])
print()
print(arr.T[:,::-1])

4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
