In [2]:
import numpy as np

# Извлечение элементов по условию

In [ ]:
По умолчанию функция where и ее параметры выглядят так:

* np.where(condition, arr1=None, arr2=None)


1 способ. np.where(condition)


В этом случае функция возвращает индексы элементов, удовлетворяющих условию condition

In [2]:
# Пример
# По умолчанию функция возвращает кортеж:

arr = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
print(np.where(arr > 7)) # (array([3, 4, 5, 7, 8, 9]),) - возвращает индексы тех значений которые подходят под условие !


# Чтобы получить numpy-массив можно обратиться по индексу:

arr = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
print(np.where(arr > 7)[0]) # [3 4 5 7 8 9]

(array([3, 4, 5, 7, 8, 9], dtype=int64),)
[3 4 5 7 8 9]


In [ ]:
2 способ

np.where(condition, x1, x2)


Проверяет условие, в случае истинности записывает в массив соответствующий элемент из x1, иначе из x2

In [3]:
# Пример
x = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
y = x * 10
print(np.where(x > 5, x, y)) # [30 50 10  8 14 17 30 10 15 18]


# Массив и число

arr = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
print(np.where(arr > 5, arr, -1)) # [-1 -1 -1  8 14 17 -1 10 15 18]

[30 50 10  8 14 17 30 10 15 18]
[-1 -1 -1  8 14 17 -1 10 15 18]


In [4]:
arr = np.array([[ 8, 18, 11],
                [17, 20,  1],
                [ 2,  4, 21],
                [16, 12, 20]]) 
print(np.where(arr < 12))

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 2, 0, 1], dtype=int64))


In [5]:
arr[np.where(arr < 12)]

array([ 8, 11,  1,  2,  4])

In [ ]:
# Задача. 

In [ ]:
# Выведите индексы столбцов, среднее в которых выше, чем среднее по массиву в целом. 

In [6]:
data = np.array([[8, 6, 5, 6],
                 [5, 9, 1, 9],
                 [8, 2, 6, 7],
                 [2, 7, 4, 4],
                 [6, 7, 6, 2],
                 [6, 9, 6, 1]])

In [15]:
all_mean = np.mean(data)

In [14]:
colunm_mean = np.mean(data, axis = 0)

In [25]:
a = np.where(colunm_mean>all_mean)[0]

In [26]:
a

array([0, 1], dtype=int64)

In [ ]:
Задача. Возьмем массу 10 пингвинов. Для одного пингвина по-прежнему не удалось собрать данные, 
поэтому np.nan нужно заменить на среднее арифметическое по массе всех остальных пингвинов. 
Выведите индексы пингвинов, масса которых лежит между 25 и 75 процентилями от массы. 

In [28]:
body_mass_10 = np.array([3750., 3800., 3250.,   np.nan, 3450., 3650., 3625., 4675., 3475., 4250.])

In [29]:
np.mean(body_mass_10)

nan

In [31]:
arr = body_mass_10[~np.isnan(body_mass_10)]

In [32]:
arr

array([3750., 3800., 3250., 3450., 3650., 3625., 4675., 3475., 4250.])

In [33]:
np.mean(arr)

3769.4444444444443

In [41]:
arr = np.where(np.isnan(body_mass_10), np.mean(arr), body_mass_10)

In [42]:
arr

array([3750.        , 3800.        , 3250.        , 3769.44444444,
       3450.        , 3650.        , 3625.        , 4675.        ,
       3475.        , 4250.        ])

In [43]:
per_25 = np.percentile(arr, 25)

In [44]:
per_25

3512.5

In [45]:
per_75 = np.percentile(arr, 75)

In [46]:
per_75

3792.3611111111113

In [51]:
np.where((arr>np.percentile(arr,25)) & (arr<np.percentile(arr,75)))

(array([0, 3, 5, 6], dtype=int64),)

# Копирование массивов

In [ ]:
Нам привычно, что присвоив одну переменную другой мы получаем ее копию:

a = 5
b = a
print(b) # 5
Однако если присвоить таким образом массив, то он не будет скопирован в полном смысле этого слова.

Пример
arr = np.array([[15, 11, 12, 13, 14],
                [ 7, 15, 16, 19, 21],
                [ 2,  5, 15, 22, 10],
                [17,  3, 24, 22, 19],
                [17, 13, 23,  1, 20]])
arr1 = arr
Теперь попробуем изменить значение в массиве arr1 и вывести новый массив

arr1[0, 0] = 1000
print(arr1)

# [[1000   11   12   13   14]
#  [   7   15   16   19   21]
#  [   2    5   15   22   10]
#  [  17    3   24   22   19]
#  [  17   13   23    1   20]]
Все отлично. А что с исходным массивом arr?

print(arr)

# [[1000   11   12   13   14]
#  [   7   15   16   19   21]
#  [   2    5   15   22   10]
#  [  17    3   24   22   19]
#  [  17   13   23    1   20]]
Он тоже изменился! Таким образом, мы получили две переменные, но на самом деле они работают с одним и тем же массивом!

Чтобы избегать таких ситуаций, используйте функцию .copy() при копировании:

arr = np.array([[15, 11, 12, 13, 14],
                [ 7, 15, 16, 19, 21],
                [ 2,  5, 15, 22, 10],
                [17,  3, 24, 22, 19],
                [17, 13, 23,  1, 20]])
arr1 = arr.copy()
Теперь в arr1 значения поменялись, а в arr - нет

arr1[0, 0] = 1000
print(arr1)

# [[1000   11   12   13   14]
#  [   7   15   16   19   21]
#  [   2    5   15   22   10]
#  [  17    3   24   22   19]
#  [  17   13   23    1   20]]

print(arr)

# [[15   11   12   13   14]
#  [   7   15   16   19   21]
#  [   2    5   15   22   10]
#  [  17    3   24   22   19]
#  [  17   13   23    1   20]]

# Подсчет значений по условию

In [ ]:
Иногда в numpy очень не хватает функции для подсчета значений. Тем не менее, существует два способа решения этой задачи: 

1. Извлечь элементы по условию и посчитать их количество с помощью .shape

arr = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
print((arr[arr >= 10]).shape[0]) # 5
2. Применить необходимое сравнение к массиву и с помощью np.sum() посчитать количество True. 
(True интерпретируется как 1, False как 0) 

arr = np.array([ 3,  5,  1,  8, 14, 17,  3, 10, 15, 18])
print((arr >= 10).sum()) # 5

In [52]:
# Задача. 

# Сколько раз числа 5 или 6 встретились в заданном одномерном массиве?

arr = np.array([4, 3, 3, 4, 5, 6, 3, 4, 6, 4])

In [54]:
(arr == 5) | (arr == 6)

array([False, False, False, False,  True,  True, False, False,  True,
       False])

In [57]:
np.sum((arr == 5) | (arr == 6))

3

In [59]:
a = arr[(arr == 5) | (arr == 6)]

In [61]:
a.shape[0]

3

In [62]:
# Задача. Подсчитать количество пингвинов-мальчиков и пингвинов-девочек, 
# если в заданном массиве 0 означает девочек, а 1 - мальчиков. 

# Выведите два числа через пробел - количество мальчиков и девочек соответственно. 

gender = np.array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [63]:
gender == 0

array([False,  True,  True,  True,  True, False,  True, False,  True,
        True])

In [64]:
gender == 1

array([ True, False, False, False, False,  True, False,  True, False,
       False])

In [66]:
print(np.sum(gender == 1), np.sum(gender == 0))

3 7


# Сортировка

In [ ]:
Сортировка массивов numpy производится только в порядке возрастания

* np.sort(x, axis=-1)

Если нужна сортировка по убыванию, то можно использовать переворот по срезу

In [ ]:
# Пример
# Стандартная сортировка

arr = np.array([19,  3,  9, 19, 10,  1,  4, 12, 16,  7])
sorted_arr = np.sort(arr) # [ 1,  3,  4,  7,  9, 10, 12, 16, 19, 19]


# Если нужна сортировка по убыванию, то можно использовать переворот по срезу

arr = np.array([19,  3,  9, 19, 10,  1,  4, 12, 16,  7])
sorted_arr = np.sort(arr)[::-1] # [19, 19, 16, 12, 10,  9,  7,  4,  3,  1]

In [67]:
arr = np.array([19,  3,  9, 19, 10,  1,  4, 12, 16,  7])

In [68]:
np.sort(arr)

array([ 1,  3,  4,  7,  9, 10, 12, 16, 19, 19])

## Сортировка двумерных массивов

In [ ]:
Если массив двумерный, то сортировать его можно по строкам или по столбцам. Но что это значит? 

Возьмем массив

arr = np.array([[17,  1, 18],
                [ 8,  6, 11],
                [15, 17,  2],
                [13,  7,  5],
                [ 6,  4,  8]])

Если используем сортировку по умолчанию c axis=-1 (то есть ничего не передадим), 
то получим массив, в котором каждая строка отсортирована по возрастанию, то есть результат, равносильный axis=1

sorted_arr = np.sort(arr)
print(sorted_arr)

# Результат
# [[ 1, 17, 18],
#  [ 6,  8, 11],
#  [ 2, 15, 17],
#  [ 5,  7, 13],
#  [ 4,  6,  8]]

Если axis=0, то получим сортировку каждого столбца

sorted_arr = np.sort(arr, axis=0)
print(sorted_arr)

# Результат
# [[ 6  1  2]
#  [ 8  4  5]
#  [13  6  8]
#  [15  7 11]
#  [17 17 18]]

In [69]:
# Задача.
# Дан двумерный массив. Отсортируйте каждый столбец в порядке неубывания. 

data = np.array([[8, 6, 5, 6],
                 [5, 9, 1, 9],
                 [8, 2, 6, 7],
                 [2, 7, 4, 4],
                 [6, 7, 6, 2],
                 [6, 9, 6, 1]])

In [72]:
np.sort(data)

array([[5, 6, 6, 8],
       [1, 5, 9, 9],
       [2, 6, 7, 8],
       [2, 4, 4, 7],
       [2, 6, 6, 7],
       [1, 6, 6, 9]])

In [73]:
np.sort(data, axis = 0)

array([[2, 2, 1, 1],
       [5, 6, 4, 2],
       [6, 7, 5, 4],
       [6, 7, 6, 6],
       [8, 9, 6, 7],
       [8, 9, 6, 9]])

In [74]:
np.sort(data, axis = 0)[::-1]

array([[8, 9, 6, 9],
       [8, 9, 6, 7],
       [6, 7, 6, 6],
       [6, 7, 5, 4],
       [5, 6, 4, 2],
       [2, 2, 1, 1]])

In [76]:
# Задача. 
#Дан двумерный массив, отсортируйте его так, 
# чтобы осортировано было не по строкам/столбцам, а по всему массиву

data = np.array([[8, 6, 5, 6],
                 [5, 9, 1, 9],
                 [8, 2, 6, 7],
                 [2, 7, 4, 4],
                 [6, 7, 6, 2],
                 [6, 9, 6, 1]])

In [78]:
arr = data.reshape(1, -1)

In [79]:
arr

array([[8, 6, 5, 6, 5, 9, 1, 9, 8, 2, 6, 7, 2, 7, 4, 4, 6, 7, 6, 2, 6, 9,
        6, 1]])

In [81]:
res = np.sort(arr)

In [82]:
res

array([[1, 1, 2, 2, 2, 4, 4, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 8, 8, 9,
        9, 9]])

In [83]:
result = res.reshape(data.shape)

In [84]:
result

array([[1, 1, 2, 2],
       [2, 4, 4, 5],
       [5, 6, 6, 6],
       [6, 6, 6, 6],
       [7, 7, 7, 8],
       [8, 9, 9, 9]])

In [ ]:
Задача. Кусочно-заданная функция.

Дан массив. Выведите сумму его значений, округленную до двух знаков после запятой, для следующей кусочно-заданной функции 

y = atan(x) при x < 0
y = 3*x + 4 при x >= 0

In [104]:
n = int(input())
x = np.linspace(-np.pi/2, 10, num=n)

50


In [105]:
x

array([-1.57079633, -1.33465763, -1.09851893, -0.86238023, -0.62624152,
       -0.39010282, -0.15396412,  0.08217458,  0.31831328,  0.55445198,
        0.79059068,  1.02672938,  1.26286808,  1.49900678,  1.73514548,
        1.97128418,  2.20742288,  2.44356158,  2.67970028,  2.91583898,
        3.15197768,  3.38811638,  3.62425509,  3.86039379,  4.09653249,
        4.33267119,  4.56880989,  4.80494859,  5.04108729,  5.27722599,
        5.51336469,  5.74950339,  5.98564209,  6.22178079,  6.45791949,
        6.69405819,  6.93019689,  7.16633559,  7.40247429,  7.63861299,
        7.8747517 ,  8.1108904 ,  8.3470291 ,  8.5831678 ,  8.8193065 ,
        9.0554452 ,  9.2915839 ,  9.5277226 ,  9.7638613 , 10.        ])

In [106]:
1/np.tan(x)

array([-6.12323400e-17, -2.40628008e-01, -5.10834258e-01, -8.56778341e-01,
       -1.38241091e+00, -2.43205378e+00, -6.44361694e+00,  1.21418100e+01,
        3.03473105e+00,  1.61486323e+00,  9.89668523e-01,  6.04971430e-01,
        3.18044682e-01,  7.19131294e-02, -1.65845044e-01, -4.23368398e-01,
       -7.39313441e-01, -1.19199717e+00, -2.00880712e+00, -4.35409869e+00,
        9.62889849e+01,  3.97389516e+00,  1.90839842e+00,  1.14292372e+00,
        7.07672110e-01,  3.99085531e-01,  1.44573923e-01, -9.28248446e-02,
       -3.41071104e-01, -6.33708355e-01, -1.03165069e+00, -1.69240922e+00,
       -3.26108489e+00, -1.62649738e+01,  5.66461497e+00,  2.29531855e+00,
        1.32362740e+00,  8.21386343e-01,  4.84915488e-01,  2.18761463e-01,
       -2.07730483e-02, -2.62714253e-01, -5.37309006e-01, -8.93452974e-01,
       -1.44467039e+00, -2.58334020e+00, -7.46339156e+00,  9.67961991e+00,
        2.83522375e+00,  1.54235105e+00])

In [107]:
3*x + 4

array([-7.12388980e-01, -3.97287874e-03,  7.04443223e-01,  1.41285932e+00,
        2.12127543e+00,  2.82969153e+00,  3.53810763e+00,  4.24652373e+00,
        4.95493983e+00,  5.66335593e+00,  6.37177204e+00,  7.08018814e+00,
        7.78860424e+00,  8.49702034e+00,  9.20543644e+00,  9.91385254e+00,
        1.06222686e+01,  1.13306847e+01,  1.20391008e+01,  1.27475170e+01,
        1.34559331e+01,  1.41643492e+01,  1.48727653e+01,  1.55811814e+01,
        1.62895975e+01,  1.69980136e+01,  1.77064297e+01,  1.84148458e+01,
        1.91232619e+01,  1.98316780e+01,  2.05400941e+01,  2.12485102e+01,
        2.19569263e+01,  2.26653424e+01,  2.33737585e+01,  2.40821746e+01,
        2.47905907e+01,  2.54990068e+01,  2.62074229e+01,  2.69158390e+01,
        2.76242551e+01,  2.83326712e+01,  2.90410873e+01,  2.97495034e+01,
        3.04579195e+01,  3.11663356e+01,  3.18747517e+01,  3.25831678e+01,
        3.32915839e+01,  3.40000000e+01])

In [108]:
z = np.zeros(n)

In [109]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
z = np.where(x<0, 1/np.tan(x), z)

In [111]:
z

array([-6.12323400e-17, -2.40628008e-01, -5.10834258e-01, -8.56778341e-01,
       -1.38241091e+00, -2.43205378e+00, -6.44361694e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00])

In [112]:
z = np.where(x>0, 3*x + 4, z)

In [113]:
z

array([-6.12323400e-17, -2.40628008e-01, -5.10834258e-01, -8.56778341e-01,
       -1.38241091e+00, -2.43205378e+00, -6.44361694e+00,  4.24652373e+00,
        4.95493983e+00,  5.66335593e+00,  6.37177204e+00,  7.08018814e+00,
        7.78860424e+00,  8.49702034e+00,  9.20543644e+00,  9.91385254e+00,
        1.06222686e+01,  1.13306847e+01,  1.20391008e+01,  1.27475170e+01,
        1.34559331e+01,  1.41643492e+01,  1.48727653e+01,  1.55811814e+01,
        1.62895975e+01,  1.69980136e+01,  1.77064297e+01,  1.84148458e+01,
        1.91232619e+01,  1.98316780e+01,  2.05400941e+01,  2.12485102e+01,
        2.19569263e+01,  2.26653424e+01,  2.33737585e+01,  2.40821746e+01,
        2.47905907e+01,  2.54990068e+01,  2.62074229e+01,  2.69158390e+01,
        2.76242551e+01,  2.83326712e+01,  2.90410873e+01,  2.97495034e+01,
        3.04579195e+01,  3.11663356e+01,  3.18747517e+01,  3.25831678e+01,
        3.32915839e+01,  3.40000000e+01])

In [114]:
np.sum(z)

810.4339379870069

In [117]:
x[x<0]

array([-1.57079633, -1.33465763, -1.09851893, -0.86238023, -0.62624152,
       -0.39010282, -0.15396412])

In [122]:
x[x>=0]

array([ 0.08217458,  0.31831328,  0.55445198,  0.79059068,  1.02672938,
        1.26286808,  1.49900678,  1.73514548,  1.97128418,  2.20742288,
        2.44356158,  2.67970028,  2.91583898,  3.15197768,  3.38811638,
        3.62425509,  3.86039379,  4.09653249,  4.33267119,  4.56880989,
        4.80494859,  5.04108729,  5.27722599,  5.51336469,  5.74950339,
        5.98564209,  6.22178079,  6.45791949,  6.69405819,  6.93019689,
        7.16633559,  7.40247429,  7.63861299,  7.8747517 ,  8.1108904 ,
        8.3470291 ,  8.5831678 ,  8.8193065 ,  9.0554452 ,  9.2915839 ,
        9.5277226 ,  9.7638613 , 10.        ])

In [124]:
np.sum(np.arctan(x[x<0])) + np.sum((3*(x[x>=0]) + 4))

817.7404539873303

# Задача. Знак числа

In [ ]:
Нужно для каждого элемента массива определить его знак. Итоговый массив формируется по следующим правилам:

1, если соответствующее число положительно
0, если соответствующее число равно нулю
-1, если соответствующее число отрицательно
Считайте массив целых чисел с клавиатуры (обратите внимание, что элементы вводятся через пробел) и выведите массив знаков sign

In [133]:
a = np.array(list(map(int,input().split())))

1 5 -9 3 9 -7 0


In [134]:
a

array([ 1,  5, -9,  3,  9, -7,  0])

In [135]:
np.where(a>0, 1, np.where(a<0, -1, np.where(a==0, 0, a)))

array([ 1,  1, -1,  1,  1, -1,  0])

In [9]:
z = np.zeros((2,2))

In [10]:
z

array([[0., 0.],
       [0., 0.]])

In [28]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

X, y = load_iris(return_X_y=True) # загрузка датасета
clf = LogisticRegression(random_state=0, max_iter=130).fit(X, y) # настройка и обучение классификатора

n = int(input())
y = y[:n] # возьмем часть правильных ответов
y_pred = clf.predict(X)[:n] # возьмем часть ответов классификатора

# Ваш код

z = np.zeros((2,2))
z[0][0] = np.sum((y==1) & (y_pred == 1))

z[0][1] = np.sum((y==1) & (y_pred == 0))
z[1][0] = np.sum((y==0) & (y_pred == 1))
z[1][1] = np.sum((y==0) & (y_pred == 0))

print(z)

60
[[10.  0.]
 [ 0. 50.]]


In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.sum((y==1) & (y_pred==1))

10