In [2]:
import numpy as np

# Сравнение массивов

### Как сравнить два массива 

In [3]:
# Мы говорили о том, что к массивам применимы все арифметические операторы и они производят поэлементные вычисления. 

# На самом деле, то же касается и операторов сравнения. С помощью ==, !=, <=, <, >, >= можно 
# поэлементно сравнить два массива. В этом случае мы получим массив значений Истина/Ложь, 

# такие массивы называют булевыми или логическими.  


#                                     1     2    False

#                                     2 ==  2 =  True

#                                     3     3    True

In [4]:
# Пример
# 1. Сравнение через оператор ==

a1 = np.array([1, 2, 3])
a2 = np.array([2, 2, 2])

print(a1 == a2) # [False  True False]

[False  True False]


In [5]:
# 2. Сравнение через оператор >

a1 = np.array([1, 2, 3])
a2 = np.array([2, 2, 2])

print(a1 > a2) # [False False  True]

[False False  True]


In [6]:
# 3. Случай, когда один массив двумерный, а другой одномерный, тоже возможен. 
# Тогда одномерный массив будет сравниваться с каждой строкой двумерного:

arr1 = np.array([[1, 2], 
                 [3, 4]])
arr2 = np.array([1, 2])
print(arr1 == arr2)
# Результат
# [[ True  True]
#  [False False]]

[[ True  True]
 [False False]]


### Сравнение массивов с числами

In [7]:
# Можно сравнивать массивы и числа. В этом случае сравниваться будет каждый элемент массива с заданным числом

# Пример

arr1 = np.array([3, 7, 5, 9])
print(arr1 > 5)
# Результат
# [False  True False  True]

[False  True False  True]


In [ ]:
# Функции-синонимы
# Каждый оператор сравнения имеет функцию-синоним

# np.greater(x1, x2) - синоним оператора > 
# np.greater_equal(x1, x2) - синоним оператора >= 
# np.less(x1, x2) - синоним оператора < 
# np.less_equal(x1, x2) - синоним оператора <= 
# np.equal(x1, x2) - синоним оператора == 
# np.not_equal(x1, x2) - синоним оператора !=

# Индексация булевыми массивами

In [ ]:
Можно не только сравнивать массивы, но и извлекать значения, подходящие по условию. 

Мы можем передавать булевы массивы в качестве индексов, тогда в результате вернется 
выборка из массива, которой в исходном массиве было сопоставлено значение True.

In [ ]:
# Пример
# Например, перед нами стоит следующая задача. Создается массив, находится 
# его среднее арифметическое и проверяется, какие элементы строго больше среднего арифметического. 
# Дальше нужно из массива выбрать и вывести эти элементы. 

arr = np.array([3, 4, 5, 1])
mean = np.mean(arr) # 3.25
condition = arr > mean # [False,  True,  True, False]
print(arr[condition]) # [4, 5]

# Чаще это записывается так

arr = np.array([3, 4, 5, 1])
mean = np.mean(arr) # 3.25
print(arr[arr > mean]) # [4, 5]

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,8,7,6,7,8,7,6,6,5,6,7,8,6,5,5,4,4,3,2,2,1,23,4,5,6,7,7,6,5,0])

In [5]:
a_mean = np.mean(a)

In [7]:
a[a>a_mean]

array([ 6,  7,  8,  9,  8,  7,  6,  7,  8,  7,  6,  6,  6,  7,  8,  6, 23,
        6,  7,  7,  6])

In [ ]:
# Но такой способ работает только, когда нам достаточно только одного условия. 
# Если бы мы хотели извлечь, все элементы, которые больше 1 и меньше 5, 
# то следующая запись была бы ошибкой

arr = np.array([3, 4, 5, 1])
print(arr[arr > 1 and arr < 5]) # Error!

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  8,  7,  6,  7,  8,  7,  6,  6,
        5,  6,  7,  8,  6,  5,  5,  4,  4,  3,  2,  2,  1, 23,  4,  5,  6,
        7,  7,  6,  5,  0])

In [16]:
# Задача

# Дан одномерный массив. Выберите и выведите из массива элементы, которые строго меньше 25 процентиля.

arr = np.array([2, 7, 7, 8, 8, 6, 8, 7, 6, 7])

In [20]:
percentile = np.percentile(arr, 25)

In [21]:
percentile

6.25

In [22]:
arr[arr<percentile]

array([2, 6, 6])

# Истинность всех элементов массива

In [ ]:
# Функция np.all() проверяет, все ли элементы массива равны True или могут преобразоваться к True  

# np.all(bool_arr, axis=None) 
# Функция np.all() принимает на вход булев массив (либо выполняет преобразование) и возвращает единственное 
# значение True или False

# Преобразование
# Целочисленные и вещественные значения при необходимости легко преобразуются в логические. 
# Любое число, кроме нуля, интерпретируется как True, а ноль интерпретируется False.

# Константы np.inf, np.NINF, np.nan тоже преобразуются к True.

In [ ]:
# Примеры
# 1. Все элементы равны True, в ответе тоже True

arr = np.array([True,  True, True,  True])
np.all(arr) # True


In [ ]:
# 2. Один из элементов равен False, в ответе будет False

arr = np.array([True,  True, False,  True])
np.all(arr) # False


In [8]:
# 3. Двумерные массивы можно проверить по осям или целиком

arr = np.array([[True,  True], 
                [False,  True]])
np.all(arr) # False 
np.all(arr, axis=0) # [False,  True]
np.all(arr, axis = 1)

array([ True, False])

# Истинность хотя бы одного элемента массива

In [ ]:
Функция np.any() проверяет, можно ли преобразовать хотя бы один из элементов к True, тогда возвращает True

np.any(bool_arr, axis=None)
Принимает на вход булев массив (либо выполняет преобразование) и возвращает единственное значение True или False

Примеры
1. Один из элементов True, поэтому в ответе тоже True

arr = np.array([True,  False, False,  False])
np.any(arr) # True


2. Все элементы False, в ответе False

arr = np.array([False,  False, False,  False])
np.any(arr) # False


3. Константы преобразуются к True

arr = np.array([True,  np.inf, np.nan,  np.NINF])
np.any(arr) # True


4. Тоже можно проверять по осям

arr = np.array([[True,  True, False], 
                [False,  True, False]])
np.any(arr, axis=0) # [ True,  True, False]


5. Целые числа, преобразованные к False

arr = np.array([0,  0, 0,  0])
np.any(arr) # False

In [ ]:
# Задача №1

In [20]:
n = int(input())

3


In [37]:
arr = np.array([list(map(int,input().split())) for i in range(n)])

1 2 3
4 5 6
7 8 9


In [39]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
print(np.any(arr, axis=0))

[ True  True  True]


In [45]:
# Задача №2

# Массив-палиндром
# Дан одномерный массив. Выведите True, если массив и его перевернутая версия равны, иначе False

arr = np.array([1, 1, 0, 1, 2])

In [46]:
arr

array([1, 1, 0, 1, 2])

In [47]:
arr[::-1]

array([2, 1, 0, 1, 1])

In [48]:
np.all(arr == arr[::-1])

False

# Проверка на равенство бесконечности

In [ ]:
Есть три функции, проверяющие равенство элементов массива и бесконечности

np.isinf(x) - проверка элементов на равенство константам np.inf или np.NINF
np.isposinf(x) - проверка элементов на равенство константе np.inf
np.isneginf(x) - проверка элементов на равенство константе np.NINF
Все эти функции принимают на вход массивы, в ответе возвращают булевы массивы

Пример
arr = np.array([5,  -np.inf, np.NINF,  np.inf])

print(np.isinf(arr)) # [False  True  True  True]

print(np.isposinf(arr)) # [False False False  True]

print(np.isneginf(arr)) # [False  True  True False]

# Проверка на нечисло

In [ ]:
Как мы уже знаем, константа np.nan не равна ни одному значению, даже сама себе. Поэтому следующая функция - единственный способ проверить значения на равенство np.nan

np.isnan(x) 
Функция принимает на вход массив или число, в ответ возвращает булев массив

Пример
arr = np.array([4,  3, np.NINF,  np.inf, np.nan])
np.isnan(arr) # [False, False, False, False,  True]
Чтобы удалить np.nan из массива: 

arr = np.array([4,  3, np.NINF,  np.inf, np.nan])
np.isnan(arr) 
arr[np.isnan(arr) == False] # [  4.,   3., -inf,  inf]
Или так

arr = np.array([4,  3, np.NINF,  np.inf, np.nan])
np.isnan(arr) 
arr[~np.isnan(arr)] # [  4.,   3., -inf,  inf]

In [50]:
arr = np.array([4,  3, np.NINF,  np.inf, np.nan])
np.isnan(arr) 
# arr[np.isnan(arr) == False] # [  4.,   3., -inf,  inf]

array([False, False, False, False,  True])

In [51]:
culmen_length_10 = np.array([39.1, 39.5, 40.3,  np.nan, 36.7, 39.3, 38.9, 39.2, 34.1, 42. ])
np.isnan(culmen_length_10)

array([False, False, False,  True, False, False, False, False, False,
       False])

# Логическое И

In [ ]:
Предположим, у нас есть две булевы переменные. К ним можно применить операцию логического И, 
которая в результате возвращает истину, если обе переменные истинны и ложь в обратном случае. 
Это аналог оператора and в условиях

In [ ]:
Функция, объединяющая два булевых массива по принципу логического И:

np.logical_and(x1, x2) - возвращает результат поэлементного применения к двум массивами операции AND
Функции этого раздела принимают на вход массивы или массив + скаляр (число или булево значение), 
в ответ возвращает булев массив. 

Пример 
1. Одномерный массив + одномерный массив

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

np.logical_and(arr1, arr2)
# [ True, False, False, False]
Напомним, что константы np.inf, np.NINF и np.nan преобразуются к истине 

2. Двумерный массив + двумерный массив

arr1 = np.array([[True, True], 
                 [False, False]])
arr2 = np.array([[True, False], 
                 [True, False]])

print(np.logical_and(arr1, arr2))
# array([[ True, False],
#        [False, False]])
3. Двумерный массив + одномерный массив

arr1 = np.array([[True, True], 
                 [False, False]])
arr2 = np.array([True, False])
print(np.logical_and(arr1, arr2))
# array([[ True, False],
#        [False, False]])
4. Одномерный массив + скаляр

arr1 = np.array([True, True, False, False])
scalar_num = 5
scalar_bool = False
print(np.logical_and(arr1, scalar_num)) # [ True,  True, False, False]
print(np.logical_and(arr1, scalar_bool)) # [False, False, False, False]

# Логическое или

In [ ]:
Функция логического ИЛИ. Возвращает истину, когда хотя бы один из аргументов является истиной, иначе возвращает ложь. 
Это аналог оператора or

np.logical_or(x1, x2) - возвращает результат поэлементного применения к двум массивами операции OR

Пример 
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

np.logical_or(arr1, arr2)
# [ True,  True,  True, False]

# Логическое НЕ

In [ ]:
Функция логического НЕ. На вход принимает всего один аргумент возвращает обратное логическое значение. 
Аналог оператора not в python

np.logical_not(x1) - возвращает результат поэлементного применения операции NOT к одному массиву

Пример 
arr1 = np.array([True, False, np.inf, np.nan])

np.logical_not(arr1)
# [False,  True, False, False]
Помните, что константы np.inf, np.NINF и np.nan преобразуются к истине, поэтому их логическое отрицание вернет нам False

arr1 = np.array([True, False, np.inf, np.nan])
print(np.logical_not(arr1))
# [False,  True, False, False]

# Исключающее ИЛИ

In [ ]:
Функция исключающего ИЛИ. Она возвращает истину, если аргументы не равны между собой, 
для одинаковых аргументов возвращается ложь

np.logical_xor(x1, x2) - возвращает результат поэлементного применения к двум массивами операции XOR


Пример 
arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])

np.logical_xor(arr1, arr2)
# [False,  True,  True, False]

In [ ]:
Нужно отметить, что вместо этих фукций (почти всегда) используются операторы:

& - логическое И;

| - логическое ИЛИ;

^ - исключающее ИЛИ;

~ - логическое НЕ.

При этом операнды необходимо заключить в скобки:

(arr > 1) & (arr < 10)
Выведет значения массива больше 1 и меньше 10. 

In [ ]:
Задача

Выведите булев массив, отвечающий на вопрос, какие из элементов данного массива больше low и меньше или равны up?

In [54]:
low = int(input())
up = int(input())
arr = np.array([9, 4, 5, 8, 9, 4])

5
9


In [55]:
np.logical_and(arr> low, arr<=up)

array([ True, False, False,  True,  True, False])

# Равенство массивов

In [ ]:
Функция np.array_equal() в целом делает то же, что и оператор сравнения ==, 
однако требует, чтобы массивы имели одинаковую размерность и позволяет считать два значения np.nan равными, если в параметр equal_nan передать True

np.array_equal(x1, x2, equal_nan=False) 
Функция принимает на вход два массива и возвращает одно булево значение

Пример
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])
np.array_equal(arr1, arr2) # True
equal_nan=True

arr1 = np.array([1, 2, 3, np.nan])
arr2 = np.array([1, 2, 3, np.nan])

np.array_equal(arr1, arr2) # False
np.array_equal(arr1, arr2, equal_nan=True) # True

# Равенство массивов с заданной точностью

In [ ]:
Не всегда возможно гарантировать точность вычислений при работе с вещественными числами. 
Поэтому numpy предоставляет две функции для сравнения массивов с заданной точностью:

* np.allclose(x1, x2, rtol=1e-05, atol=1e-08, equal_nan=False) - сравнение элементов с заданной точностью. 
В ответ возвращает одно значение True или False


* np.isclose(x1, x2, rtol=1e-05, atol=1e-08, equal_nan=False) - сравнение элементов с заданной точностью. 
В ответ возвращает массив True или False


Элементы считаются равными, если выполняется следующее условие:

absolute(x1 - x2) <= (atol + rtol * absolute(x2)), где rtol - относительная погрешность, atol - абсолютная погрешность

Пример
arr1 = np.array([1.1, 2.12, 3.11, 4.5])
arr2 = np.array([[1.0, 2.0, 3.0, 4.0]])

np.allclose(arr1, arr2, atol=0.5) # True
np.isclose(arr1, arr2, atol=0.5) # [ True,  True,  True,  True]

In [ ]:
# Задача№1. Равенство с точностью до 0.05

# Дан массив и вводится целое число n. Выведите в ответ булев массив, в котором True будет означать, 
# что соответствующий элемент заданного массива равен n с абсолютной погрешностью 0.05 и False в противном случае. 

# Формат входных данных
# На вход подается единственное целое число

# Формат выходных данных
# Программа должна вывести одномерный логический массив

In [56]:
n = int(input())
data = np.array([0.45, 0.97, 1.01 , 1.95, 0.54, 0.3 , 0.04])

1


In [59]:
np.isclose(data, n, atol = 0.05)

array([False,  True,  True, False, False, False, False])

In [62]:
n = np.array(list(map(int,input().split())))

1 2 3 4 5 6


In [63]:
n

array([1, 2, 3, 4, 5, 6])

# Проверка значений в массиве

In [ ]:
np.isin(element, test_elements, invert=False)

Проверяет наличие element - массива или числа - в test_elements. 
Возвращает логический массив той же формы, что и element. 
В этом массиве True означает, что элемент есть в массиве, иначе False. 

Если invert=True, то в ответе наоборот False означает присутствие элемент, иначе True.

Пример
arr = np.array([2, 4, 9, 8, 1, 7, 8, 8, 5, 5])
element = np.array([1, 3, 5])
np.isin(element, arr) # [ True, False,  True]


Если invert=True

arr = np.array([2, 4, 9, 8, 1, 7, 8, 8, 5, 5])
element = np.array([1, 3, 5])
np.isin(element, arr, invert=True) # [False,  True, False]


Массив и число

arr = np.array([2, 4, 9, 8, 1, 7, 8, 8, 5, 5])
np.isin(2, arr) # [ True]


np.nan не будет найден таким способом

arr = np.array([np.nan, 4, 9, 8, 1, 7, 8, 8, 5, 5])
element = np.array([np.nan, 3, 5])
print(np.isin(element, arr)) # [False, False,  True]

In [ ]:
Двумерный случай
arr = np.array([[ 8, 3, 11],
                [17, 20,  1],
                [ 2,  4, 21],
                [16, 12, 20]]) 
element = np.array([ 3, 5])
print(np.isin(element, arr)) # [ True, False]

# ЗАДАЧИ ПО ТЕМЕ

In [66]:
# №1 Лотерейные билеты

# Василий купил лотерейный билет и загадал число. На лотрейном билете написано несколько чисел, 
# выведите True, если среди них оказалось загаданное Василием, иначе выведите False.

# Формат входных данных
# На вход единственное целое число, которое загадал Василий

# Формат выходных данных
# Программа должна вывести True или False

data = np.array([ 7,  3,  1, 19, 11])

n = int(input())

print(np.isin(n,data))

3
True


In [ ]:
# №2 Соревнования по программированию

# Проводились соревнования по программированию, всего было 5 заданий. 
# Первый этап был отборочным и если участник не набрал пороговый балл (5),
# то он мог принимать дальше участие, но не мог стать призером. 
# А призерами становились участники, набравшие больше 7 баллов за каждое из оставшихся заданий. 
# Выведите баллы призеров.

# Формат входных данных
# В первой строке вводится n - количество участников. Затем двумерный целочисленный массив размерностью nx5

# Формат выходных данных
# Программа должна вывести двумерный целочисленный массив - баллы призеров




In [175]:
n = int(input())
arr = np.array([list(map(int,input().split())) for i in range(n)])

5
8 8 8 8 8
2 9 7 8 8
2 9 6 9 3
5 9 9 6 6
5 4 2 1 9


In [ ]:
# 5
# 8 8 8 8 8
# 2 9 7 8 8
# 2 9 6 9 3
# 5 9 9 6 6
# 5 4 2 1 9

In [166]:
# 6
# 2  2  5  7  4
# 6  5  9  1  7
# 9  2  5  8  1
# 5  9  9  9  8
# 8  8  8  4  7
# 6  8  8  9 10

In [ ]:
# 3
# 4  9  9  9  8
# 8  8  8  4  7
# 6  8  8  9 10

In [176]:
arr

array([[8, 8, 8, 8, 8],
       [2, 9, 7, 8, 8],
       [2, 9, 6, 9, 3],
       [5, 9, 9, 6, 6],
       [5, 4, 2, 1, 9]])

In [177]:
arr>=5

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False,  True]])

In [178]:
izbrann = arr[arr[:,0]>=5]

In [179]:
izbrann

array([[8, 8, 8, 8, 8],
       [5, 9, 9, 6, 6],
       [5, 4, 2, 1, 9]])

In [181]:
izbrann_without_first = izbrann[:,1:]

In [182]:
izbrann_without_first

array([[8, 8, 8, 8],
       [9, 9, 6, 6],
       [4, 2, 1, 9]])

In [183]:
np.all(izbrann_without_first>7, axis = 1)

array([ True, False, False])

In [185]:
izbrann[np.all(izbrann>7, axis=1)]

array([[8, 8, 8, 8, 8]])

In [142]:
n = int(input())

arr = np.array( [ list( map (int,input().split()))  for i in range(n)]   )



3
5 6 9
5 6 9
1 2 3


In [143]:
arr

array([[5, 6, 9],
       [5, 6, 9],
       [1, 2, 3]])

In [144]:
izb = arr[arr[:,0] > 2]

In [145]:
izb

array([[5, 6, 9],
       [5, 6, 9]])

In [146]:
izb[np.all(izb>4, axis = 1)]

array([[5, 6, 9],
       [5, 6, 9]])

### Задача. Стандартное отклонение по длине плавника 2

In [ ]:
Ранее нужно было вычислить границы стандартного отклонения массива по правилу трех сигм. Напомним, что  99,73% 
выборки будут лежать в интервале 

Xсреднее_арифм - 3*sigma - Xсреднее_арифм + 3*sigma

В этом задании вам снова даны длины плавников 10 пингвинов, нужно вывести True, 
если все они лежат в указанном интервале и False в противном случае. 

Напомним, что в массиве присутствует константа np.nan. Замените ее на среднее значение остальных элементов массива. 

Формат входных данных
В этом задании нет входных данных, вам нужно обработать массив, заданный в шаблоне

Формат выходных данных
Программа должна единственный отве: True или False

In [215]:
flipper_length_10 = np.array([181., 186., 195.,  np.nan, 193., 190., 181., 195., 193., 190.])

In [218]:
mask = np.isnan(flipper_length_10)

In [219]:
arr = flipper_length_10[~mask]

array([181., 186., 195., 193., 190., 181., 195., 193., 190.])

In [190]:
arr = np.nan_to_num(flipper_length_10)

In [191]:
sigma = np.std(arr)

In [193]:
sigma*3

171.03789053890952

In [194]:
arr_mean = np.mean(arr)

In [195]:
arr_mean

170.4

In [208]:
low = arr_mean - sigma*3

In [209]:
low

-0.6378905389095166

In [210]:
up = arr_mean + sigma*3

In [211]:
up

341.4378905389095

In [205]:
arr[(arr>=low)]

array([181., 186., 195.,   0., 193., 190., 181., 195., 193., 190.])

In [213]:
np.all((arr>=low) & (arr<=up) )

True

In [223]:
flipper_length_10 = np.array([181., 186., 195.,  np.nan, 193., 190., 181., 195., 193., 190.])
mask = np.isnan(flipper_length_10)
arr = flipper_length_10[~mask]
print(arr)

arr_mean = np.mean(arr)
sigma = np.std(arr)
low = arr_mean - 3*sigma
up = arr_mean + 3*sigma

print(np.all((arr>=low) & (arr<=up)))

[181. 186. 195. 193. 190. 181. 195. 193. 190.]
True
